set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk]
set_property PACKAGE_PIN P17  [get_ports clk]


set_property PACKAGE_PIN D5 [get_ports segs0[0]]
set_property PACKAGE_PIN B2 [get_ports segs0[1]]
set_property PACKAGE_PIN B3 [get_ports segs0[2]]
set_property PACKAGE_PIN A1 [get_ports segs0[3]]
set_property PACKAGE_PIN B1 [get_ports segs0[4]]
set_property PACKAGE_PIN A3 [get_ports segs0[5]]
set_property PACKAGE_PIN A4 [get_ports segs0[6]]
set_property PACKAGE_PIN B4 [get_ports segs0[7]]

set_property PACKAGE_PIN H2 [get_ports segs1[0]]
set_property PACKAGE_PIN D2 [get_ports segs1[1]]
set_property PACKAGE_PIN E2 [get_ports segs1[2]]
set_property PACKAGE_PIN F3 [get_ports segs1[3]]
set_property PACKAGE_PIN F4 [get_ports segs1[4]]
set_property PACKAGE_PIN D3 [get_ports segs1[5]]
set_property PACKAGE_PIN E3 [get_ports segs1[6]]
set_property PACKAGE_PIN D4 [get_ports segs1[7]]

set_property PACKAGE_PIN G6 [get_ports len[0]]
set_property PACKAGE_PIN E1 [get_ports len[1]]
set_property PACKAGE_PIN F1 [get_ports len[2]]
set_property PACKAGE_PIN G1 [get_ports len[3]]
set_property PACKAGE_PIN H1 [get_ports len[4]]
set_property PACKAGE_PIN C1 [get_ports len[5]]
set_property PACKAGE_PIN C2 [get_ports len[6]]
set_property PACKAGE_PIN G2 [get_ports len[7]]

set_property PACKAGE_PIN T5 [get_ports user_password[0]]
set_property PACKAGE_PIN T3 [get_ports user_password[1]]
set_property PACKAGE_PIN R3 [get_ports user_password[2]]
set_property PACKAGE_PIN V4 [get_ports user_password[3]]
set_property PACKAGE_PIN V5 [get_ports user_password[4]]
set_property PACKAGE_PIN V2 [get_ports user_password[5]]
set_property PACKAGE_PIN U2 [get_ports user_password[6]]
set_property PACKAGE_PIN U3 [get_ports user_password[7]]
set_property PACKAGE_PIN R1 [get_ports user_password[8]]
set_property PACKAGE_PIN N4 [get_ports user_password[9]]
set_property PACKAGE_PIN M4 [get_ports user_password[10]]
set_property PACKAGE_PIN R2 [get_ports user_password[11]]
set_property PACKAGE_PIN P2 [get_ports user_password[12]]
set_property PACKAGE_PIN P3 [get_ports user_password[13]]
set_property PACKAGE_PIN P4 [get_ports user_password[14]]
set_property PACKAGE_PIN P5 [get_ports user_password[15]]

set_property PACKAGE_PIN F6 [get_ports LED[0]]
set_property PACKAGE_PIN G4 [get_ports LED[1]]
set_property PACKAGE_PIN G3 [get_ports LED[2]]
set_property PACKAGE_PIN J4 [get_ports LED[3]]
set_property PACKAGE_PIN H4 [get_ports LED[4]]
set_property PACKAGE_PIN J3 [get_ports LED[5]]
set_property PACKAGE_PIN J2 [get_ports LED[6]]
set_property PACKAGE_PIN K2 [get_ports LED[7]]
set_property PACKAGE_PIN K1 [get_ports LED[8]]
set_property PACKAGE_PIN H6 [get_ports LED[9]]
set_property PACKAGE_PIN H5 [get_ports LED[10]]
set_property PACKAGE_PIN J5 [get_ports LED[11]]
set_property PACKAGE_PIN K6 [get_ports LED[12]]
set_property PACKAGE_PIN L1 [get_ports LED[13]]
set_property PACKAGE_PIN M1 [get_ports LED[14]]
set_property PACKAGE_PIN K3 [get_ports LED[15]]

set_property PACKAGE_PIN U4 [get_ports check_bag]
set_property PACKAGE_PIN R17 [get_ports get_bag]
set_property PACKAGE_PIN R11 [get_ports make_sure]
set_property PACKAGE_PIN V1 [get_ports to_input]
set_property PACKAGE_PIN R15 [get_ports restart]

#·Ö¸îÏß#
set_property IOSTANDARD LVCMOS33 [get_ports clk]

set_property IOSTANDARD LVCMOS33 [get_ports segs0[7]]
set_property IOSTANDARD LVCMOS33 [get_ports segs0[6]]
set_property IOSTANDARD LVCMOS33 [get_ports segs0[5]]
set_property IOSTANDARD LVCMOS33 [get_ports segs0[4]]
set_property IOSTANDARD LVCMOS33 [get_ports segs0[3]]
set_property IOSTANDARD LVCMOS33 [get_ports segs0[2]]
set_property IOSTANDARD LVCMOS33 [get_ports segs0[1]]
set_property IOSTANDARD LVCMOS33 [get_ports segs0[0]]

set_property IOSTANDARD LVCMOS33 [get_ports segs1[7]]
set_property IOSTANDARD LVCMOS33 [get_ports segs1[6]]
set_property IOSTANDARD LVCMOS33 [get_ports segs1[5]]
set_property IOSTANDARD LVCMOS33 [get_ports segs1[4]]
set_property IOSTANDARD LVCMOS33 [get_ports segs1[3]]
set_property IOSTANDARD LVCMOS33 [get_ports segs1[2]]
set_property IOSTANDARD LVCMOS33 [get_ports segs1[1]]
set_property IOSTANDARD LVCMOS33 [get_ports segs1[0]]

set_property IOSTANDARD LVCMOS33 [get_ports len[7]]
set_property IOSTANDARD LVCMOS33 [get_ports len[6]]
set_property IOSTANDARD LVCMOS33 [get_ports len[5]]
set_property IOSTANDARD LVCMOS33 [get_ports len[4]]
set_property IOSTANDARD LVCMOS33 [get_ports len[3]]
set_property IOSTANDARD LVCMOS33 [get_ports len[2]]
set_property IOSTANDARD LVCMOS33 [get_ports len[1]]
set_property IOSTANDARD LVCMOS33 [get_ports len[0]]

set_property IOSTANDARD LVCMOS33 [get_ports user_password[0]]
set_property IOSTANDARD LVCMOS33 [get_ports user_password[1]]
set_property IOSTANDARD LVCMOS33 [get_ports user_password[2]]
set_property IOSTANDARD LVCMOS33 [get_ports user_password[3]]
set_property IOSTANDARD LVCMOS33 [get_ports user_password[4]]
set_property IOSTANDARD LVCMOS33 [get_ports user_password[5]]
set_property IOSTANDARD LVCMOS33 [get_ports user_password[6]]
set_property IOSTANDARD LVCMOS33 [get_ports user_password[7]]
set_property IOSTANDARD LVCMOS33 [get_ports user_password[8]]
set_property IOSTANDARD LVCMOS33 [get_ports user_password[9]]
set_property IOSTANDARD LVCMOS33 [get_ports user_password[10]]
set_property IOSTANDARD LVCMOS33 [get_ports user_password[11]]
set_property IOSTANDARD LVCMOS33 [get_ports user_password[12]]
set_property IOSTANDARD LVCMOS33 [get_ports user_password[13]]
set_property IOSTANDARD LVCMOS33 [get_ports user_password[14]]
set_property IOSTANDARD LVCMOS33 [get_ports user_password[15]]

set_property IOSTANDARD LVCMOS33 [get_ports LED[0]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[1]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[2]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[3]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[4]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[5]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[6]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[7]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[8]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[9]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[10]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[11]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[12]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[13]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[14]]
set_property IOSTANDARD LVCMOS33 [get_ports LED[15]]

set_property IOSTANDARD LVCMOS33 [get_ports check_bag]
set_property IOSTANDARD LVCMOS33 [get_ports get_bag]
set_property IOSTANDARD LVCMOS33 [get_ports make_sure]
set_property IOSTANDARD LVCMOS33 [get_ports to_input]
set_property IOSTANDARD LVCMOS33 [get_ports restart]


